---
# ============================================================================
# INFRASTRUCTURE DEPLOYMENT
# ============================================================================
# This playbook manages Azure infrastructure deployment:
# - Resource groups with auto-cleanup tags
# - Virtual networks and subnets
# - Network security groups with streaming-specific rules
# - Storage for container and VM networking
# ============================================================================

- name: Deploy Streaming Infrastructure
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    event_name: "{{ event_name | default('streaming-event') }}"
    resource_group: "streaming-{{ event_name }}-{{ ansible_date_time.epoch }}"
    azure_location: "{{ azure_location | default('East US') }}"

    # Network configuration
    vnet_address_space: "10.42.0.0/16"
    container_subnet: "10.42.1.0/24"
    mixer_subnet: "10.42.2.0/24"

  tasks:
    - name: Create Resource Group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ azure_location }}"
        tags:
          purpose: streaming
          event: "{{ event_name }}"
          created_by: ansible
          environment: "{{ deployment_environment | default('production') }}"
      tags: [deploy, resource_group]

    # ========================================================================
    # NETWORKING INFRASTRUCTURE
    # ========================================================================
    - name: Create Virtual Network
      azure.azcollection.azure_rm_virtualnetwork:
        name: "streaming-vnet"
        resource_group: "{{ resource_group }}"
        address_prefixes: "10.42.0.0/16"
        tags:
          purpose: streaming-network
          event: "{{ event_name }}"
      tags: [deploy, networking]

    - name: Create Container Subnet
      azure.azcollection.azure_rm_subnet:
        name: "containers"
        virtual_network: "streaming-vnet"
        resource_group: "{{ resource_group }}"
        address_prefix: "10.42.1.0/24"
      tags: [deploy, networking]

    - name: Create Mixer Subnet
      azure.azcollection.azure_rm_subnet:
        name: "mixers"
        virtual_network: "streaming-vnet"
        resource_group: "{{ resource_group }}"
        address_prefix: "10.42.2.0/24"
      tags: [deploy, networking]

    - name: Create Container Network Security Group
      azure.azcollection.azure_rm_securitygroup:
        name: "streaming-containers-nsg"
        resource_group: "{{ resource_group }}"
        tags:
          purpose: container-security
          event: "{{ event_name }}"
        rules:
          - name: AllowSRT
            protocol: Tcp
            destination_port_range: 9998
            access: Allow
            priority: 1000
            direction: Inbound
          - name: AllowSplitter
            protocol: Tcp
            destination_port_range: 9999
            access: Allow
            priority: 1001
            direction: Inbound
          - name: AllowHTTP
            protocol: Tcp
            destination_port_range: 8080
            access: Allow
            priority: 1002
            direction: Inbound
          - name: AllowSSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1003
            direction: Inbound
      tags: [deploy, networking, security]

    - name: Create Mixer Network Security Group
      azure.azcollection.azure_rm_securitygroup:
        name: "streaming-mixers-nsg"
        resource_group: "{{ resource_group }}"
        tags:
          purpose: mixer-security
          event: "{{ event_name }}"
        rules:
          - name: AllowRDP
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1000
            direction: Inbound
          - name: AllowWinRM
            protocol: Tcp
            destination_port_range: 5986
            access: Allow
            priority: 1001
            direction: Inbound
          - name: AllowRTMP
            protocol: Tcp
            destination_port_range: 1935
            access: Allow
            priority: 1002
            direction: Inbound
          - name: AllowHTTP
            protocol: Tcp
            destination_port_range: 8080
            access: Allow
            priority: 1003
            direction: Inbound
      tags: [deploy, networking, security]

    # ========================================================================
    # STORE INFRASTRUCTURE FACTS
    # ========================================================================
    - name: Store infrastructure facts for other playbooks
      ansible.builtin.set_fact:
        streaming_resource_group: "{{ resource_group }}"
        streaming_location: "{{ azure_location }}"
        streaming_vnet: "streaming-vnet"
        container_subnet: "containers"
        mixer_subnet: "mixers"
        container_nsg: "streaming-containers-nsg"
        mixer_nsg: "streaming-mixers-nsg"
      delegate_to: localhost
      delegate_facts: true

    - name: Display infrastructure summary
      ansible.builtin.debug:
        msg:
          - "============================================"
          - "🏗️  INFRASTRUCTURE READY"
          - "============================================"
          - "Resource Group: {{ resource_group }}"
          - "Location: {{ azure_location }}"
          - "Virtual Network: streaming-vnet (10.42.0.0/16)"
          - "Container Subnet: containers (10.42.1.0/24)"
          - "Mixer Subnet: mixers (10.42.2.0/24)"
          - "Network Security Groups:"
          - "  - Container NSG: streaming-containers-nsg"
          - "  - Mixer NSG: streaming-mixers-nsg"
          - ""
          - "Ready for resource deployment!"
          - "============================================"
      tags: [always]
